name: '⌛️ Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on:
      - ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: dryRun
        uses: ./
        with:
          helmChartUrl: oci://myregistry.example.com/mycompanyinc/auth-service
          helmChartVersion: 1.2.3
          githubSecretVariablePrefix: PROJECTX
          deploymentEnvironment: DEV
          namespace: project-x
          helmConfigMapVariableName: config
          helmSecretVariableName: secrets
          helmEnvVarVariableName: envVars
          kubeConfig: 'dummyConfigAsThisIsJustAdryRun'
          secrets: ${{ toJson(secrets) }}
          variables: ${{ toJson(vars) }}
          environmentVariables: '{ "NODE_OPTIONS": "--max-old-space-size=8192", "JAVA_OPTS": "-Xms128m -Xmx256g", "SPRING_PROFILES_ACTIVE": "k8s,dev" }'
          tag: 'dummyimgtag'
          dryRun: true
